global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'burnout-api'

rule_files:
  # - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
