_wandb:
    value:
        cli_version: 0.24.2
        e:
            ooy7i9ako979bs6r8d2eznq1rjuruapq:
                codePath: scripts\train_model.py
                codePathLocal: scripts\train_model.py
                cpu_count: 16
                cpu_count_logical: 22
                disk:
                    /:
                        total: "1021821579264"
                        used: "337843666944"
                email: kakarlagana18@gmail.com
                executable: C:\Users\lenovo\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: b743fca07f712b0903c87e65caa56a8fbd9a9878
                    remote: https://github.com/ganapathi-ai/Employment_burnout_prediction.git
                host: GANAPATHI-LENOVO
                memory:
                    total: "33752997888"
                os: Windows-11-10.0.26200-SP0
                program: c:\Users\lenovo\Documents\Employers_Burnout_prediction\scripts\train_model.py
                python: CPython 3.13.0
                root: c:\Users\lenovo\Documents\Employers_Burnout_prediction
                startedAt: "2026-02-14T06:09:19.124031Z"
                writerId: ooy7i9ako979bs6r8d2eznq1rjuruapq
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 5
                - 6
                - 53
                - 105
            "2":
                - 5
                - 6
                - 53
                - 105
            "3":
                - 15
                - 16
            "4": 3.13.0
            "5": 0.24.2
            "8":
                - 2
                - 3
            "12": 0.24.2
            "13": windows-amd64
dataset:
    value: work_from_home_burnout
features:
    value: 17
models:
    value:
        - RandomForest
        - GradientBoosting
        - XGBoost
n_estimators:
    value: 100
random_state:
    value: 42
test_size:
    value: 0.2
